/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Multicall2__factory } from "./Multicall2__factory";
export { Multicall3__factory } from "./Multicall3__factory";
