/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multicall2 } from "./Multicall2";
export type { Multicall3 } from "./Multicall3";
export * as factories from "./factories";
export { Multicall2__factory } from "./factories/Multicall2__factory";
export { Multicall3__factory } from "./factories/Multicall3__factory";
